# Generated by Django 3.0.8 on 2020-07-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Наименование производителя')),
                ('slug', models.SlugField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='CartParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Имя параметра')),
                ('param', models.CharField(db_index=True, max_length=20, verbose_name='Значение параметра')),
            ],
            options={
                'verbose_name': 'Параметр картриджа',
                'verbose_name_plural': 'Параметры картриджа',
            },
        ),
        migrations.CreateModel(
            name='ClassCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Класс картриджа (лазерный, струйный, матричный)')),
                ('slug', models.SlugField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Класс картриджа',
                'verbose_name_plural': 'Класс картриджей',
            },
        ),
        migrations.CreateModel(
            name='DeviceParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Имя параметра')),
                ('param', models.CharField(db_index=True, max_length=1000, verbose_name='Значение параметра')),
            ],
            options={
                'verbose_name': 'Параметр устройства',
                'verbose_name_plural': 'Параметры устройства',
            },
        ),
        migrations.CreateModel(
            name='TypeCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Тип картриджа (тонер-картридж, драм-картридж, фузер и т.д..)')),
                ('name_rus', models.CharField(blank=True, max_length=20, verbose_name='Тип картриджа (тонер-картридж, драм-картридж, фузер и т.д..) на русском')),
                ('slug', models.SlugField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Тип картриджа',
                'verbose_name_plural': 'Тип картриджей',
            },
        ),
        migrations.CreateModel(
            name='TypeDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Тип аппарата (принтер, копир, мфу')),
                ('slug', models.SlugField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Тип устройств',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Наименование устройства')),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('deviceparam', models.ManyToManyField(to='dcart.DeviceParam', verbose_name='Параметры устройства')),
                ('typedevice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcart.TypeDevice', verbose_name='Тип устройства...')),
            ],
            options={
                'verbose_name': 'Модель устройства',
                'verbose_name_plural': 'Модели устройства',
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Наименование расходника')),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcart.Brand', verbose_name='Бренд расходника')),
                ('cartparam', models.ManyToManyField(to='dcart.CartParam', verbose_name='Параметры картриджа')),
                ('classcart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcart.ClassCart', verbose_name='Класс расходника')),
                ('device', models.ManyToManyField(to='dcart.Device', verbose_name='В каких устройствах...')),
                ('typecart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcart.TypeCart', verbose_name='Тип расходника')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
    ]
